from tkinter import *
f=open('demo.txt','w')
def note():
    rno=Entry.get(st_rno)
    name=Entry.get(st_name)
    age=Entry.get(st_age)
    city=Entry.get(st_city)
    a=(rno,name,age,city)
    for i in a:
        f.write(i)
        f.write('\t')
    f.write("\n")
a=Tk()
a.title('home')
a.geometry('600x400')
st_head=Label(a,text='student details',font=('arial',16)).place(x=200,y=2)
stl_rno=Label(a,text='student rno',font=('italy',16)).place(x=100,y=100)
stl_name=Label(a,text='studentname',font=('italy',16)).place(x=100,y=150)
stl_age=Label(a,text='student age',font=('italy',16)).place(x=100,y=200)
stl_city=Label(a,text='student city',font=('italy',16)).place(x=100,y=250)
st_rno=Entry(a,font=("times",16),width=20)
st_name=Entry(a,font=("times",16),width=20)
st_age=Entry(a,font=("times",16),width=20)
st_city=Entry(a,font=("times",16),width=20)
st_rno.place(x=250,y=103)
st_name.place(x=250,y=153)
st_age.place(x=250,y=203)
st_city.place(x=250,y=253)
st_btn=Button(a,text='submit',font=('italy',16),command=note)
st_btn.place(x=300,y=300)
a.mainloop()
f.close()
